# flake8: noqa

"""
    Argo Workflows API

<<<<<<< HEAD
    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/  # noqa: E501
=======
    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/  # noqa: E501
>>>>>>> draft-3.6.5

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""


__version__ = "0.0.0-pre"

# import ApiClient
from argo_workflows.api_client import ApiClient

# import Configuration
from argo_workflows.configuration import Configuration

# import exceptions
from argo_workflows.exceptions import OpenApiException
from argo_workflows.exceptions import ApiAttributeError
from argo_workflows.exceptions import ApiTypeError
from argo_workflows.exceptions import ApiValueError
from argo_workflows.exceptions import ApiKeyError
from argo_workflows.exceptions import ApiException
